name: "Build Changelog"
uses: mikepenz/release-changelog-builder-action@{latest-release}
with:
  configuration: "configuration.yml"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  fromTag: "04.2023"