name: Contributor of the Month

on:
  push:
    branches:
      - your-branch-name

jobs:
  calculate-contributor-of-the-month:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Calculate contributor of the month
        id: calculate
        run: |
          # Get the last month's start and end dates
          LAST_MONTH_START=$(date -d "1 month ago" -I)
          LAST_MONTH_END=$(date -d "$(date +%Y-%m-01) -1 day" -I")

          # Fetch the pull requests merged in the last month
          PRS=$(git log --merges --since="$LAST_MONTH_START" --until="$LAST_MONTH_END" --pretty=format:'%H' | wc -l)

          echo "Number of merged pull requests in the last month: $PRS"
