name: Display Contributors

on:
  push:
    branches:
      - fix-404

jobs:
  contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Contributors
        run: |
          git fetch origin "+refs/pull/*/head:refs/remotes/origin/pr/*"
          git log --pretty=format:'%an <%ae>' | sort -fu
