name: Display Contributors

on:
  push:
    branches:
      - fix-404

jobs:
  github-collaborator-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Organization Repository Collaborator Action
        uses: nicklegan/github-org-repo-collaborator-action@v2.0.0

        with:
          token: ${{ secrets.ORG_TOKEN }}
          days: '30'
        # org: ''
        # affil: 'ALL'
        # permission: 'ADMIN'
        # days: '90'
        # json: 'FALSE'
        # appid: ${{ secrets.APPID }}
        # privatekey: ${{ secrets.PRIVATEKEY }}
        # installationid: ${{ secrets.INSTALLATIONID }}