name: Display Contributors

on:
  push:
    branches:
      - fix-404

jobs:
  contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Contributors
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          BASE_URL="https://api.github.com"
          REPO_URL="${BASE_URL}/spryker/spryker-docs"
          CONTRIBUTORS_URL="${REPO_URL}/contributors"
          DATE=$(date -u +"%Y-%m-01T00:00:00Z" -d "1 month ago")
          HEADERS="Accept: application/vnd.github.v3+json"
          AUTH_HEADER="Authorization: Bearer ${TOKEN}"
          curl -sSL -H "${HEADERS}" -H "${AUTH_HEADER}" "${CONTRIBUTORS_URL}?since=${DATE}" | jq -r '.[].login'