name: Contributor of the Month

on:
  push:
    branches:
      - fix-404

jobs:
  calculate-contributor-of-the-month:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Calculate contributor of the month
        id: calculate
        run: |
          # Get the last month's start and end dates
          LAST_MONTH_START=$(date -d "1 month ago" -I)
          LAST_MONTH_END=$(date -d "$(date +%Y-%m-01) -1 day" -I)

          # Fetch the merged pull requests in the last month
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=master&sort=merged&direction=desc" \
            | jq --raw-output --arg start "$LAST_MONTH_START" --arg end "$LAST_MONTH_END" \
            'map(select(.merged_at >= $start and .merged_at <= $end)) | map(.user.login) | unique[]')

          # Calculate the number of PRs per contributor
          CONTRIBUTORS=$(echo "$PRS" | sort | uniq -c | sort -nr)

          # Find the highest number of PRs
          MAX_PRS=$(echo "$CONTRIBUTORS" | head -n1 | awk '{print $1}')

          # Filter contributors with the highest number of PRs
          WINNERS=$(echo "$CONTRIBUTORS" | awk -v max="$MAX_PRS" '$1 == max {print $2}')

          echo "Contributors of the Month: $WINNERS"